### ISSUE TITLE
Default coordinates go to nothing

### ISSUE THREAD

**Issue by besimhu** [40Digits/craftgmaps#19]
Have you considered adding Springfield or another location as the default? Currently the default coordinates when left unchanged, they default to nothing. So when the field is actually loaded, it just displays a gray map. 

Springfield coordinates: Latitude: 37.2152778 Longitude: -93.2980556

**Comment by dhahn** [comment]
Yeah that's a good idea. I would rather put the lat and lng to your house though. Mind providing those?

**Comment by hahnzilla** [comment]
@besimhu check out commit 6c46fc4ab2f96db382650056d5962fbddddf23dd. Made the settings required. So it won't fix it for any fields that you have already created, but for all new fields it makes the defaultLat and defaultLng required.
