### ISSUE TITLE
Add documentation link to github in the plugin

### ISSUE THREAD

**Issue by besimhu** [40Digits/craftgmaps#22]
I'd suggest adding a documentation link to the plugin. Nothing as frustrating as trying to figure out where the documentation for the plugin may be at a later time when trying to visit.

https://craftcms.com/support/updating-plugins-for-craft-2.5

```public function getDocumentationUrl()
{
    return 'https://craftcommerce.com/docs';
}```

**Comment by dhahn** [comment]
Yeah, that's a great idea. There's a few other helpful options you can add. I'll check into that when I get some time.
